<?php
/**
 * Created by PhpStorm.
 * User: Neff
 * Date: 06.02.2017
 * Time: 22:10
 */

namespace lesha724\treeview;


use yii\web\AssetBundle;

class TreeViewAsset extends AssetBundle
{
    public static $customCss = null;
    public $sourcePath = '@vendor/lesha724/yii2-tree-view/assets/treeview';

    public $css = [
    ];

    public $js = [
        'jquery.treeview.js'
    ];

    public $depends = [
        'yii\web\JqueryAsset',
    ];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->css = $this->_getCss();
    }

    /**
     * @return string
     */
    protected function _getCss(){
        if(!empty(static::$customCss)) {
            return[static::$customCss];
        }else{
            return['jquery.treeview.css'];
        }
    }
}